### ISSUE TITLE
passthrough mode servicebinding aliases not supported

### ISSUE THREAD

**Issue by esnible** [istio-ecosystem/emcee#2]
Fixed for passthrough binding pushed ... still working on boundary protection alias.

Current situation:

After running _test/integration/bp.sh_ I can `delete` _samples/limited-trust/helloworld-binding.yaml_ and `apply` _alias-binding-helloworld-as-holaworld.yaml_.  I expect to be able to perform `kubectl --context $CLUSTER1 exec -it cli1 -- curl --silent holaworld:5000/hello -v` but it fails with a 503.  I have tried manually tinkering with the mc2019 created Istio config but have not yet had success.

**Comment by mbanikazemi** [comment]
Done
