### ISSUE TITLE
Adding support for running the controller in the cluster

### ISSUE THREAD

**Issue by mbanikazemi** [istio-ecosystem/emcee#30]

**Comment by esnible** [comment]
Do you have a plan for this?

`go test ./...` doesn't work.  Should it?
`docker build . -t controller:latest` doesn't work:

``` 
build command-line-arguments: cannot load github.com/istio-ecosystem/emcee/pkg/discovery: cannot find module providing package github.com/istio-ecosystem/emcee/pkg/discovery
```

Does it make sense for me to remove the testing framework, which is producing a false positive failure, and recode the _Dockerfile_?

**Comment by mbanikazemi** [comment]
I think the first priority is running the controller in a container/pod. That will allow us to run it locally, in the cluster, or in a cluster different from the one being controlled.
